// Recurring-schedule ticker: every ~10s, spawns one task per due schedule and
// advances next_run_at. Guarded by a Postgres advisory lock (like the reaper)
// so only one server instance runs it at a time.
import type { PoolClient } from "pg";
import { pool } from "./db.js";
import { emitEvent } from "./events.js";
import { mapScheduleRow, type ScheduleRow } from "./rowMappers.js";
import { nextRun } from "./scheduling.js";

// Arbitrary fixed key for the scheduler's advisory lock (distinct from the
// reaper's 42_424_242).
const ADVISORY_LOCK_KEY = 42_424_243;
const TICK_INTERVAL_MS = 10_000;
// Catch-up guard: if next_run_at has drifted arbitrarily far into the past
// (server was down, etc.), cap how many times we call nextRun to walk it
// forward before giving up on this tick (nextRun itself also caps iterations).
const MAX_CATCHUP_ADVANCES = 1000;

interface DueScheduleRow extends ScheduleRow {
  project_name: string;
}

async function fetchDueSchedules(client: PoolClient): Promise<DueScheduleRow[]> {
  const result = await client.query<DueScheduleRow>(
    `SELECT s.*, p.name AS project_name
     FROM schedules s
     JOIN projects p ON p.id = s.project_id
     WHERE s.enabled AND s.next_run_at <= now()
     FOR UPDATE OF s SKIP LOCKED`
  );
  return result.rows;
}

/** Builds the payload for a fired slot, adding shift_start/shift_end when applicable. */
function buildPayload(
  schedule: DueScheduleRow,
  firedSlot: Date
): Record<string, unknown> {
  const payload: Record<string, unknown> = { ...(schedule.payload_template ?? {}) };
  if (schedule.shift_hours !== null && schedule.shift_hours !== undefined) {
    const shiftEnd = new Date(firedSlot.getTime() + schedule.shift_hours * 3600_000);
    payload.shift_start = firedSlot.toISOString();
    payload.shift_end = shiftEnd.toISOString();
  }
  return payload;
}

async function spawnTaskForSchedule(
  client: PoolClient,
  schedule: DueScheduleRow,
  firedSlot: Date
): Promise<{ taskId: string } | null> {
  const payload = buildPayload(schedule, firedSlot);

  const result = await client.query<{ id: string }>(
    `INSERT INTO tasks
       (project_id, type, payload, tags, required_capabilities, target_group_id, schedule_id, status)
     VALUES ($1, $2, $3::jsonb, $4, $5, $6, $7, 'PENDING')
     RETURNING id`,
    [
      schedule.project_id,
      schedule.type,
      JSON.stringify(payload),
      schedule.tags ?? [],
      schedule.required_capabilities ?? [],
      schedule.target_group_id,
      schedule.id,
    ]
  );
  const row = result.rows[0];
  return row ? { taskId: row.id } : null;
}

/**
 * Computes the fired slot (== old next_run_at, the due occurrence) and the
 * schedule's new next_run_at, applying the catch-up guard: if the schedule is
 * far behind (many missed slots), we still only spawn ONE task this tick, and
 * we advance next_run_at to the next FUTURE occurrence (skipping the backlog)
 * rather than flooding the queue with every missed slot.
 */
function advanceSchedule(schedule: DueScheduleRow): { firedSlot: Date; newNextRun: Date } {
  const firedSlot = new Date(schedule.next_run_at);
  let newNextRun = nextRun(schedule.recurrence, firedSlot);

  // If next_run_at is still due immediately (heavy backlog), keep walking
  // forward from the fired slot until we land on a future time — bounded so a
  // pathological recurrence can't loop forever.
  let advances = 0;
  while (newNextRun.getTime() <= Date.now() && advances < MAX_CATCHUP_ADVANCES) {
    newNextRun = nextRun(schedule.recurrence, newNextRun);
    advances += 1;
  }

  return { firedSlot, newNextRun };
}

async function processDueSchedule(client: PoolClient, schedule: DueScheduleRow): Promise<void> {
  const { firedSlot, newNextRun } = advanceSchedule(schedule);

  const spawned = await spawnTaskForSchedule(client, schedule, firedSlot);
  if (!spawned) {
    throw new Error(`Failed to spawn task for schedule ${schedule.id}`);
  }

  await client.query(
    `UPDATE schedules SET
        last_run_at = $2,
        next_run_at = $3,
        runs_count  = runs_count + 1
     WHERE id = $1`,
    [schedule.id, firedSlot.toISOString(), newNextRun.toISOString()]
  );

  const schedulePublic = mapScheduleRow(schedule);

  emitEvent({
    type: "schedule.fired",
    project_id: schedule.project_id,
    project_name: schedule.project_name,
    task_id: spawned.taskId,
    task_type: schedule.type,
    message: `Schedule "${schedule.name}" fired (slot ${firedSlot.toISOString()})`,
  });
  emitEvent({
    type: "task.published",
    project_id: schedule.project_id,
    project_name: schedule.project_name,
    task_id: spawned.taskId,
    task_type: schedule.type,
    status: "PENDING",
    message: `Generated by schedule "${schedulePublic.name}"`,
  });
}

async function tick(): Promise<void> {
  const client = await pool.connect();
  try {
    const lockResult = await client.query<{ locked: boolean }>(
      "SELECT pg_try_advisory_lock($1) AS locked",
      [ADVISORY_LOCK_KEY]
    );
    if (!lockResult.rows[0]?.locked) {
      // Another instance holds the lock this tick.
      return;
    }

    try {
      await client.query("BEGIN");
      const due = await fetchDueSchedules(client);
      for (const schedule of due) {
        await processDueSchedule(client, schedule);
      }
      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK").catch(() => undefined);
      console.error("[scheduler] error processing due schedules", err);
    } finally {
      await client.query("SELECT pg_advisory_unlock($1)", [ADVISORY_LOCK_KEY]);
    }
  } catch (err) {
    console.error("[scheduler] error acquiring advisory lock", err);
  } finally {
    client.release();
  }
}

let intervalHandle: NodeJS.Timeout | null = null;

export function startScheduler(): void {
  if (intervalHandle) return;
  intervalHandle = setInterval(() => void tick(), TICK_INTERVAL_MS);
  // Run once immediately so a schedule due right at boot doesn't wait a full tick.
  void tick();
}

export function stopScheduler(): void {
  if (intervalHandle) {
    clearInterval(intervalHandle);
    intervalHandle = null;
  }
}
